export const GET_PRAYER_REQUESTS = 'GET_PRAYER_REQUESTS';
export const GET_PRAYER_REQUESTS_ERROR = 'GET_PRAYER_REQUESTS_ERROR';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const USER_LOADED = 'USER_LOADED';
export const USER_LOADED_ERROR = 'USER_LOADED_ERROR';
